### ISSUE TITLE
Failed to start gRPC mock server

### ISSUE THREAD

**Issue by jduan-highnote** [Fadelis/grpcmock#12]
We have lots of tests that start gRPC mock servers. Even though they all set the port to 0 so a random port is selected, there's still a chance that two tests try to use the same random port. See the screenshot below.

Is there a way to configure the mock server so it retries a few times when seeing such an error? Thanks!

<img width="1185" alt="Cursor_and_Build_Scan™_for__platform-bennet__on_Jan_31_2022_at_8_07_53_PM_PST___Gradle_Enterprise" src="https://user-images.githubusercontent.com/92047874/152450086-90b701aa-e835-47ff-ba70-7ac62503f6a2.png">

**Comment by Fadelis** [comment]
Currently there's no such feature. Do you create so many gRPC mock servers for unit or it testing? Since if it's for unit testing you might want to try using [InProcessGrpcMockExtension](https://github.com/Fadelis/grpcmock#junit5)

**Comment by jduan-highnote** [comment]
Thanks for your quick response! I'll give the InProcessGrpcMockExtension a try. I might also add retries when the server fails to bind to a port.

**Comment by Fadelis** [comment]
Closing, since there's no further discussions.
