### ISSUE TITLE
How to mock Grpc Method .withRequest with one unknown field

### ISSUE THREAD

**Issue by Radnaeva** [Fadelis/grpcmock#17]
How to mock Grpc Method with request with one unknown field?

stubFor(unaryMethod(UserGrpc.getCreateMethod())
                .withRequest(UserOuterClass.CreateUserReq.newBuilder()
                        .setEmail(email)
                        .setPassword(      any()     )   <--------- this field? 
                        .build()
                )
                .willReturn(UserOuterClass.User.newBuilder()
                        .setId(userId)
                        .build()
                )
        );

I tried Mockito's any() etc. It doesn't work

**Comment by Fadelis** [comment]
Hi @Radnaeva, this library does not use any of the Mockito's constructs, but even in Mockito, your usage of `any()` would be incorrect.

If you can't match your request object fully via `.equals` method, then you have to use the `Predicate` form of `withRequest` method. Then you can do one of the following:
1. Match each individual property you're interested in:
```java
.withRequest(req -> req.getEmail().equals("some@email")
    && req.getName().equals("Some Name")) 
```
2. Or remove properties that are not know from the request and match to your partial objects:
```java
.withRequest(req -> req.toBuilder().clearPassword().equals(CreateUserReq.newBuilder()
    .setEmail(email)
    .build()))
```
