### ISSUE TITLE
Enhancement: Add 'willProxyTo' to all communication types

### ISSUE THREAD

**Issue by RomanKhachko** [Fadelis/grpcmock#18]
Currently, the interface StreamRequestProxyResponseBuilderStep is implemented by classes supporting streaming from the client-side (client and bidi streams). However, it would be extremely beneficial to add this functionality for other communication types (server stream and unary).

We use this library not for testing purposes, but as an embedded mock server for our local development experience. Method 'willProxyTo' allows providing a custom dynamic behavior. Therefore, besides predefined responses, we could provide implementations handling request values in runtime.

**Comment by Fadelis** [comment]
Hi @RomanKhachko , this is already available for both unary and server streaming requests. There's a method `.willProxyTo((request, responseObserver) -> ...)`, where you control the whole flow, and also `.willReturn(request -> ...)` where you can respond based on the request and will complete the call that call for you after this function completes. You can see more examples [here](https://github.com/Fadelis/grpcmock/blob/2ffbbbca6d8e030a0da15218e90d3ca21ef38d80/grpcmock-core/src/test/java/org/grpcmock/GrpcMockUnaryMethodTest.java#L280-L361) and [here](https://github.com/Fadelis/grpcmock/blob/2ffbbbca6d8e030a0da15218e90d3ca21ef38d80/grpcmock-core/src/test/java/org/grpcmock/GrpcMockServerStreamingMethodTest.java#L437-L521)

**Comment by RomanKhachko** [comment]
Amazing! Thanks a lot for the clarification! It's exactly what is needed. I will remove the request then in order not to pollute your board.
