### ISSUE TITLE
Support StubMapping in JSON

### ISSUE THREAD

**Issue by zheng-wang** [Fadelis/grpcmock#19]
Hello. Is there currently any plan to support StubMapping like [the equivalence](https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/stubbing/StubMapping.java) in WireMock?

StubMapping enables storing stub definitions/specifications in plain JSONs, and loading them back to set up all the stubs in the mock server. It opens the window for users without Java skills to set up gRPC stubs easily, and opens another window for GUIed tools to integrate/embed the grpcmock framework in their frameworks.

**Comment by Fadelis** [comment]
Hi @zheng-wang , this is a very similar request to #7 , so I'll close yours.
As mentioned there initially I intended this to be used through DSL for unit or IT tests, not as a standalone server. I'll keep this in mind, but currently I don't think that I'll be working on this. 
Also maybe there are similar projects out there, that probably fit your use better. Eg. check out https://github.com/Adven27/grpc-wiremock project.
