### ISSUE TITLE
How to mock service by this if provided a proto file 

### ISSUE THREAD

**Issue by Rank2019** [Fadelis/grpcmock#2]
now I got one proto file , if i want mock grpc sevrice by this proto ,how can i integrate this project with my request , i check your example , it's hard for me to understand , btw ,i am new in grpc cycle . tks

**Comment by Fadelis** [comment]
@Rank2019 first you'll have to generate Java stubs for your given file. gRPC stubs are generated using `protoc` binary, or using a maven/gradle plugin, which take cares of finding the right `protoc` binary for you. Here are some useful starting links - [Link #1](https://grpc.io/docs/languages/java/generated-code/) [Link #2](https://www.baeldung.com/grpc-introduction)

If you're new to gRPC I'd suggest to follow some small guide, where you'd implement a gRPC client and a server, then you could move to testing them.

As this is not related to the library itself, I'm closing this.
