### ISSUE TITLE
Allow integration tests to run in parallell - bug?

### ISSUE THREAD

**Issue by MelkerForssell** [Fadelis/grpcmock#20]
Hi,
I have a problem with running integration tests in parallel which I solved and I just wanted to notify you about the problem. It seems like the grpcmock is shared between tests. (Atleast in the way I am using it)

I am unable to use the `@AutoConfigureGrpcMock` since I am using the starter from https://github.com/yidongnan/grpc-spring-boot-starter and need to set the address via `@DynamicPropertySource` like this:
```
@DynamicPropertySource
    static void overwriteProperties(DynamicPropertyRegistry registry) {
        registry.add("grpc.client.<client>.address") { "static://localhost:$GrpcMock.globalPort()" }
    }
```

I start the server like this:
```
    def setupSpec() {
        grpcMock = GrpcMock.grpcMock().build().start()
        GrpcMock.configureFor(grpcMock)
    }
```

When I run tests in parallel I will get an error with the port being taken.

I found the following in your code and it turns out that the `socket.setReuseAddress(true);` in `findFreePort` is what is causing the issue, so by removing it is resolved. 

```
 private static int findFreePort() {
    try (ServerSocket socket = new ServerSocket(0)) {
      return socket.getLocalPort();
    } catch (IOException e) {
      throw new GrpcMockException("Failed finding a free port", e);
    }
  }
```

**Comment by Fadelis** [comment]
Yes, that can be removed. Thanks for reporting.
