### ISSUE TITLE
Access to gRPC Mock server from outer client

### ISSUE THREAD

**Issue by FedorSabeshkin** [Fadelis/grpcmock#26]
Do I understand correctly that with this library, i can raise a real gRPC service, on the host and port that I specified, which will be available from the outside?

For example, can the gRPC client launched by me separately (for example, in a separate JVM), call a method defined in this server, and then inside the test, I can call verify() to check that the method that the client accessed was called on the server and with what kind of arguments.

**Comment by FedorSabeshkin** [comment]
Yes, it works as i described in the text above :).

**Comment by Fadelis** [comment]
Hi @FedorSabeshkin , yes potentially you could run it in a separate JVM and call it via the defined port on that machine. But the main use case for gRPC Mock is to run it in the same process as your application and use it in you Junit5 or IT tests. You read more info in the [integrations](https://github.com/Fadelis/grpcmock#integrations) section.

**Comment by FedorSabeshkin** [comment]
@Fadelis, hello!

Yes, i want use it for Integration Test, where i will be start gRPC client, which will be connect to gRPC server by host and port.

**Comment by FedorSabeshkin** [comment]
In this case Mockito.verify() will't work for my service?
