### ISSUE TITLE
How to stub both gRPC and Rest (GET/POST) endpoint?

### ISSUE THREAD

**Issue by harshmah** [Fadelis/grpcmock#3]
I have a service which is based on gRPC. But that having both types of downstreams:
1. Web Server - Call them via GET/POST.
2. gRPC Server - Call them via gRPC.

Can we use gRPCMock to stub both endpoints? If yes, please share an example.

**Comment by Fadelis** [comment]
Hi, gRPC Mock is only for mocking downstream gRPC services. For http ones I'd suggest to use Wiremock.
